### ISSUE TITLE
使用离线模式时报"段错误 (core dumped)"

### ISSUE THREAD

**Issue by leafonsword** [session-replay-tools/tcpcopy#316]
运行时报错
```
./tcpcopy -i online.pcap -x 3306-${target_ip}:3306 -s ${assistant_ip} -c ${client_ip} -C 11 -n 10 -l t.log
段错误 (core dumped)   
```
t.log日志是：
```
2018/02/06 16:56:16 +246 [notice] tcpcopy version:1.0.0
2018/02/06 16:56:16 +246 [notice] tcpcopy internal version:6
2018/02/06 16:56:16 +246 [notice] target:3306-10.21.111.13:3306
2018/02/06 16:56:16 +246 [notice] TC_OFFLINE mode
2018/02/06 16:56:16 +246 [notice] TC_COMBINED mode
2018/02/06 16:56:16 +246 [notice] TC_PLUGIN mode
2018/02/06 16:56:16 +246 [notice] TC_PAYLOAD is true
2018/02/06 16:56:16 +246 [notice] epoll mode
2018/02/06 16:56:16 +246 [notice] session timeout:120
2018/02/06 16:56:16 +246 [notice] keepalive timeout:240
2018/02/06 16:56:16 +246 [notice] min sess pool size:624
2018/02/06 16:56:16 +246 [notice] sess pool size:1024
2018/02/06 16:56:16 +246 [notice] repl num:10
2018/02/06 16:56:16 +246 [notice] set global port for tcpcopy
2018/02/06 16:56:16 +246 [notice] raw_clt_tf_ip:10.3.13.139
2018/02/06 16:56:16 +246 [notice] parallel connections per target:4
2018/02/06 16:56:16 +246 [notice] accelerated 1 times,interval:0 ms
2018/02/06 16:56:16 +246 [notice] s parameter:10.21.111.9
2018/02/06 16:56:16 +246 [notice] set only ip for tcpcopy
2018/02/06 16:56:16 +246 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:56:16 +246 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:56:16 +246 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:56:16 +246 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:56:16 +246 [notice] open pcap success:online.pcap
2018/02/06 16:56:16 +246 [notice] send the first packets here
2018/02/06 16:57:24 +517 [notice] tcpcopy version:1.0.0
2018/02/06 16:57:24 +517 [notice] tcpcopy internal version:6
2018/02/06 16:57:24 +517 [notice] target:3306-10.21.111.13:3306
2018/02/06 16:57:24 +517 [notice] TC_OFFLINE mode
2018/02/06 16:57:24 +517 [notice] TC_COMBINED mode
2018/02/06 16:57:24 +517 [notice] TC_PLUGIN mode
2018/02/06 16:57:24 +517 [notice] TC_PAYLOAD is true
2018/02/06 16:57:24 +517 [notice] epoll mode
2018/02/06 16:57:24 +517 [notice] session timeout:120
2018/02/06 16:57:24 +517 [notice] keepalive timeout:240
2018/02/06 16:57:24 +517 [notice] min sess pool size:624
2018/02/06 16:57:24 +517 [notice] sess pool size:1024
2018/02/06 16:57:24 +517 [notice] repl num:10
2018/02/06 16:57:24 +517 [notice] set global port for tcpcopy
2018/02/06 16:57:24 +517 [notice] raw_clt_tf_ip:10.3.13.139
2018/02/06 16:57:24 +517 [notice] parallel connections per target:4
2018/02/06 16:57:24 +517 [notice] accelerated 1 times,interval:0 ms
2018/02/06 16:57:24 +517 [notice] s parameter:10.21.111.9
2018/02/06 16:57:24 +517 [notice] set only ip for tcpcopy
2018/02/06 16:57:24 +517 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:57:24 +517 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:57:24 +517 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:57:24 +517 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:57:24 +517 [notice] open pcap success:online.pcap
2018/02/06 16:57:24 +517 [notice] send the first packets here
2018/02/06 16:58:13 +523 [notice] tcpcopy version:1.0.0
2018/02/06 16:58:13 +523 [notice] tcpcopy internal version:6
2018/02/06 16:58:13 +523 [notice] target:3306-10.21.111.13:3306
2018/02/06 16:58:13 +523 [notice] TC_OFFLINE mode
2018/02/06 16:58:13 +523 [notice] TC_COMBINED mode
2018/02/06 16:58:13 +523 [notice] TC_PLUGIN mode
2018/02/06 16:58:13 +523 [notice] TC_PAYLOAD is true
2018/02/06 16:58:13 +523 [notice] epoll mode
2018/02/06 16:58:13 +523 [notice] session timeout:120
2018/02/06 16:58:13 +523 [notice] keepalive timeout:240
2018/02/06 16:58:13 +523 [notice] min sess pool size:624
2018/02/06 16:58:13 +523 [notice] sess pool size:1024
2018/02/06 16:58:13 +523 [notice] repl num:10
2018/02/06 16:58:13 +523 [notice] set global port for tcpcopy
2018/02/06 16:58:13 +523 [notice] raw_clt_tf_ip:10.3.13.139
2018/02/06 16:58:13 +523 [notice] parallel connections per target:11
2018/02/06 16:58:13 +523 [notice] accelerated 1 times,interval:0 ms
2018/02/06 16:58:13 +523 [notice] s parameter:10.21.111.9
2018/02/06 16:58:13 +523 [notice] set only ip for tcpcopy
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [info] connect to remote server(10.21.111.9:36524)
2018/02/06 16:58:13 +523 [notice] open pcap success:online.pcap
2018/02/06 16:58:13 +523 [notice] send the first packets here
```

**Comment by lazio579** [comment]
能够贴出崩溃时程序的backtrace吗？

**Comment by leafonsword** [comment]
@lazio579 
不会backtrace，给下代码或命令？

**Comment by lazio579** [comment]
首先设置ulimit -c unlimited
然后运行tcpcopy，等待崩溃，就会产生core文件
然后类似gdb ./tcpcopy core文件，输出bt，就会打印出backtrace，顺便info lo看看变量，把这些信息发过来即可或者发到邮箱(wangbin579@gmail.com)

**Comment by leafonsword** [comment]
@lazio579 
谢谢，我试下

**Comment by leafonsword** [comment]
@lazio579 
```
(gdb) bt
#0  0x000000000040373a in get_link_list (table=0x0, key=152888001832287) at src/core/tc_hash.h:34
#1  0x0000000000403816 in hash_find_link_node (table=0x0, key=152888001832287) at src/core/tc_hash.c:27
#2  0x00000000004039d5 in hash_find (table=0x0, key=152888001832287) at src/core/tc_hash.c:80
#3  0x0000000000411368 in remove_or_refresh_fir_auth (key=152888001832287, is_refresh=0)
    at mysql-replay-module/tc_mysql_module.c:120
#4  0x0000000000411706 in release_resources (key=152888001832287)
    at mysql-replay-module/tc_mysql_module.c:238
#5  0x000000000040e85c in tc_proc_ingress (ip=0x2279660, tcp=0x2279674)
    at src/tcpcopy/tc_session.c:2452
#6  0x00000000004083f0 in dispose_packet (packet=0x2279660 "E", ip_rcv_len=52,
    p_valid_flag=0x7fff516ee628) at src/tcpcopy/tc_packets_module.c:378
#7  0x0000000000408b8f in send_packets_from_pcap (first=1) at src/tcpcopy/tc_packets_module.c:625
#8  0x0000000000408785 in tc_open_and_read_pcap_file (pcap_file=0x7fff516f0644 "online.pcap")
    at src/tcpcopy/tc_packets_module.c:467
#9  0x00000000004087c6 in tc_offline_init (event_loop=0x64ad20, pcap_file=0x7fff516f0644 "online.pcap")
    at src/tcpcopy/tc_packets_module.c:490
#10 0x0000000000407e9b in tcp_copy_init (ev_lp=0x64ad20) at src/tcpcopy/tc_manager.c:245
#11 0x0000000000410280 in main (argc=15, argv=0x7fff516ee8e8) at src/tcpcopy/main.c:1140
```

**Comment by leafonsword** [comment]
@lazio579 
```
(gdb) bt
#0  0x000000000040373a in get_link_list (table=0x0, key=152888001832287) at src/core/tc_hash.h:34
#1  0x0000000000403816 in hash_find_link_node (table=0x0, key=152888001832287) at src/core/tc_hash.c:27
#2  0x00000000004039d5 in hash_find (table=0x0, key=152888001832287) at src/core/tc_hash.c:80
#3  0x0000000000411368 in remove_or_refresh_fir_auth (key=152888001832287, is_refresh=0)
    at mysql-replay-module/tc_mysql_module.c:120
#4  0x0000000000411706 in release_resources (key=152888001832287)
    at mysql-replay-module/tc_mysql_module.c:238
#5  0x000000000040e85c in tc_proc_ingress (ip=0x2279660, tcp=0x2279674)
    at src/tcpcopy/tc_session.c:2452
#6  0x00000000004083f0 in dispose_packet (packet=0x2279660 "E", ip_rcv_len=52,
    p_valid_flag=0x7fff516ee628) at src/tcpcopy/tc_packets_module.c:378
#7  0x0000000000408b8f in send_packets_from_pcap (first=1) at src/tcpcopy/tc_packets_module.c:625
#8  0x0000000000408785 in tc_open_and_read_pcap_file (pcap_file=0x7fff516f0644 "online.pcap")
    at src/tcpcopy/tc_packets_module.c:467
#9  0x00000000004087c6 in tc_offline_init (event_loop=0x64ad20, pcap_file=0x7fff516f0644 "online.pcap")
    at src/tcpcopy/tc_packets_module.c:490
#10 0x0000000000407e9b in tcp_copy_init (ev_lp=0x64ad20) at src/tcpcopy/tc_manager.c:245
#11 0x0000000000410280 in main (argc=15, argv=0x7fff516ee8e8) at src/tcpcopy/main.c:1140
```

**Comment by lazio579** [comment]
Fixed
