### ISSUE TITLE
http请求可以正常回放，grpc无法回放

### ISSUE THREAD

**Issue by DongtianA** [session-replay-tools/tcpcopy#360]
回放grpc请求时，测试服务收到了请求，但是报错了
2019-10-03 17:05:31.985 ERROR 22326 --- [worker-ELG-3-38] io.grpc.netty.NettyServerTransport       : Transport failed

io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000004080000000000000000090000080600000000000204
 at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:288) ~[netty-codec-http2-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:221) ~[netty-codec-http2-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413) [netty-codec-http2-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [netty-codec-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [netty-codec-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-codec-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar!/:4.1.11.Final]
 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [netty-common-4.1.11.Final.jar!/:4.1.11.Final]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

回放grpc请求时抓到的包，帮忙看下是什么原因
![image](https://user-images.githubusercontent.com/33851943/66204329-369e0f80-e6dd-11e9-9052-cfeecbbc4771.png)

**Comment by wangbin579** [comment]
tcpcopy支持http 2， 但需要满足如下条件才能回放：
1、捕获到完整的tcp session（包括三次握手）
2、不能丢包，一旦丢包，此tcp session回放就会被中断
